#include "Utils.hxx"

Utils::Utils() {
}

QStringList const Utils::CATEGORIES =
  QStringList()
    << "Adobe"
    << "Assurance"
    << "Banque"
    << "Cadeau donné"
    << "Cadeau reçu"
    << "Charges"
    << "Cinéma"
    << "Coiffeur"
    << "Courses"
    << "Deezer"
    << "Déménagement"
    << "Dessin"
    << "Divers"
    << "Don"
    << "EDF"
    << "Escalade"
    << "Électronique"
    << "Free"
    << "Immobilier"
    << "Impôts"
    << "Jeux vidéo"
    << "LaPoste"
    << "LEGO"
    << "Livres"
    << "Livret A"
    << "Loisirs"
    << "Loyer"
    << "Médecin"
    << "Meubles"
    << "Musée"
    << "Note de frais"
    << "PEL"
    << "Pharmacie"
    << "Pokémon"
    << "Qwerty"
    << "Restaurant"
    << "Retrait"
    << "Salaire"
    << "SNCF"
    << "Transports"
    << "Travaux"
    << "Vêtements"
    << "Unknown";
